export const Colors = {
  Blue: {
    15: '#eff4fa',
    50: '#c8daee',
    100: '#93b7de',
    200: '#7da8d7',
    300: '#528bca',
    400: '#3d7dc3',
    500: '#276fbd',
    600: '#2263aa',
    700: '#1e5897',
    800: '#1c4d84',
    900: '#174271',
  },
  Neutral: {
    100: '#fcfcfd',
    200: '#f9fafb',
    300: '#f2f4f7',
    400: '#e4e7ec',
    450: '#e6eaef',
    500: '#d0d5dd',
    600: '#98a2b3',
    700: '#475367',
    800: '#1d2939',
    900: '#101828',
  },
  Emerald: {
    100: '#f0fdf8',
    200: '#e2fbf4',
    300: '#d0f3ed',
    400: '#bde7e3',
    500: '#a4d8d8',
    600: '#77b4b9',
    700: '#528e9b',
    800: '#346a7d',
    900: '#1f4f67',
  },
  Error: {
    300: '#ffc2b7',
    500: '#ff5448',
  },
  Warning: {
    300: '#fff5ab',
    500: '#ffde0b',
  },
  Success: {
    300: '#cbffce',
    500: '#0aa06e',
  },
};

export const BoxShadow = {
  Box: {
    color: '#0052b440',
    type: 'dropShadow',
    x: '0',
    y: '2',
    blur: '2',
    spread: '0',
  },
};

export const FontFamilies = {
  BeVietnamPro: 'Be Vietnam Pro',
};

export const LineHeights = {
  0: '120%',
  1: '150%',
};

export const FontWeights = {
  BeVietnamProExtraBold: 'ExtraBold',
  BeVietnamProBold: 'Bold',
  BeVietnamProRegular: 'Regular',
};

export const FontSizes = {
  0: 9,
  1: 12,
  2: 14,
  3: 16,
  4: 18,
  5: 24,
  6: 28,
  7: 36,
  8: 42,
  9: 54,
  10: 64,
  11: 72,
};

export const LetterSpacing = {
  0: '0%',
  1: '3%',
};

export const Typography = {
  Display: {
    Large: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProExtraBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[11],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Medium: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProExtraBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[10],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Small: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProExtraBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[9],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  Heading: {
    One: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[8],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Two: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[7],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Three: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[0],
      fontSize: FontSizes[6],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Four: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[5],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    FourSmall: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[4],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    FourXSmall: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[2],
      letterSpacing: LetterSpacing[0],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Five: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[1],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    FiveXSmall: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProBold,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[0],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  Body: {
    SuperSmall: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProRegular,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[0],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Small: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProRegular,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[1],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Medium: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProRegular,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[2],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
    Large: {
      fontFamily: FontFamilies.BeVietnamPro,
      fontWeight: FontWeights.BeVietnamProRegular,
      lineHeight: LineHeights[1],
      fontSize: FontSizes[3],
      letterSpacing: LetterSpacing[1],
      paragraphSpacing: '0',
      paragraphIndent: '0',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
};

export const BorderRadius = {
  Small: 10,
  Big: 32,
  None: 0,
};
